apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: k8s
spec:
  interval: 1m
  chart:
    spec:
      chart: kube-prometheus-stack
      version: '>=65.2.0 <66.0.0'
      sourceRef:
        kind: HelmRepository
        name: prometheus-community
        namespace: flux-system
  valuesFrom:
    - kind: ConfigMap
      name: prometheus-values
