prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    retention: 10d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

grafana:
  adminPassword: Admin@Dozee  # Replace with your desired password

  service:
    type: ClusterIP
    port: 80

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

    config:
      global:
        resolve_timeout: 5m

      route:
        group_by: ['alertname', 'job']
        group_wait: 30s
        group_interval: 5m
        repeat_interval: 12h
        receiver: 'slack-notifications'

      receivers:
        - name: 'slack-notifications'
          slack_configs:
            - channel: '#demo-gcp-po-restart'
              api_url: 'https://hooks.slack.com/services/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'
              send_resolved: true
              title: |-
                [{{ .Status | toUpper }}{{ if eq .Status "firing" }}:{{ .Alerts.Firing | len }}{{ end }}] 
                {{ .CommonLabels.alertname }} for {{ .CommonLabels.job }}
              text: |-
                {{ range .Alerts -}}
                *Alert:* `{{ .Annotations.summary }}`
                *Status:* `{{ .Status | toUpper }}`
                *Description:* {{ .Annotations.description }}
                *Details:* {{ range .Labels.SortedPairs }}• *{{ .Name }}:* `{{ .Value }}`{{ end }}
                {{ end }}

kubeControllerManager:
  enabled: true

kubeScheduler:
  enabled: true

nodeExporter:
  enabled: true

# Additional Alert Rules for Pod Restart Monitoring
additionalPrometheusRulesMap:
  - rule-name: custom-alert
    groups:
      - name: pod-restart-alert
        rules:
          - alert: PodRestart
            annotations:
              description: 'Pod {{ $labels.pod }} in namespace {{ $labels.namespace }} restarted more than 1 time in the last 5 minutes.'
              summary: 'Pod Restart Alert'
            expr: rate(kube_pod_container_status_restarts_total[5m]) * 300 > 1
            for: 5m
            labels:
              severity: critical
