prometheus:
  prometheusSpec:
    serviceMonitorSelector: {}
    podMonitorSelector: {}
    retention: 10d
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

grafana:
  admin:
    enabled: true
    password: admin  # Replace with your desired password

  service:
    type: ClusterIP
    port: 80

alertmanager:
  alertmanagerSpec:
    resources:
      requests:
        cpu: 100m
        memory: 256Mi
      limits:
        cpu: 200m
        memory: 512Mi

kubeControllerManager:
  enabled: true

kubeScheduler:
  enabled: true

nodeExporter:
  enabled: true

# Additional configurations can be added below
