apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - helm-release.yaml
  # - service-prometheus.yaml
configMapGenerator:
  - name: prometheus-values
    files:
      - values.yaml=helm-values.yaml
configurations:
  - kustomizeconfig.yaml
